#################-PACMAN CONF-#################
chaotic_repo_include = True
noextract_lines = [
    "NoExtract = etc/xdg/autostart/firewall-applet.desktop",
    "NoExtract = usr/share/icons/capitaine-cursors/*",
]
#############-PACMAN CONF-#############
pkgs = [
    ############-Amd-############
    "mesa",
    "xf86-video-amdgpu",
    "xf86-video-ati",
    "vulkan-radeon",
    ##########-Nvidia-##########
    "lib32-nvidia-utils",
    "libva-nvidia-driver",
    "libva-utils",
    "libxnvctrl",
    "nvidia-open",
    "nvidia-prime",
    "opencl-nvidia",
    #########-Pipewire-#########
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "gst-plugin-pipewire",
    "libpulse",
    "wireplumber",
    #########-Hardware-#########
    "ananicy-cpp",
    "bluetui",
    "bluez-utils",  # for loggy
    "brightnessctl",
    "btop",
    "rocm-smi-lib",  # btop dependency for amd gpu
    "dosfstools",
    "exfatprogs",
    "gvfs-mtp",  # Nemo/Android
    "ntfs-3g",
    "nvtop",
    "partitionmanager",
    "powertop",
    "realtime-privileges",
    "smartmontools",
    "tlp",
    "udisks2-btrfs",
    "usb_modeswitch",
    #########-Network-#########
    "bind",
    "deluge-gtk",
    "firewalld",
    "impala",
    "kdeconnect",
    "openresolv",
    "profile-sync-daemon",
    "protonmail-bridge",
    "sshfs",
    "wireguard-tools",
    "wireless-regdb",
    ########-Lang/Fonts-########
    "font-manager",
    "hunspell-en_us",
    "hyphen-en",
    "noto-fonts-emoji",
    "otf-firamono-nerd",
    "rofimoji",
    "tesseract-data-eng",
    "ttf-hack-nerd",
    "ttf-liberation"
    ########-Multimedia-########
    "cava",
    "evince",
    "gimp",
    "guvcview",
    "imv",
    "mpd",
    "mpd-mpris",
    "mpv-mpris",
    "pavucontrol",
    "playerctl",
    "rmpc",
    "yt-dlp",
    ###########-CLI-############
    "alacritty",
    "aria2",
    "bash-completion",
    "bat-extras",
    "eza",
    "fd",
    "fzf",
    "github-cli",
    "lazygit",
    "less",
    "man-pages",
    "mcfly",
    "rebuild-detector",
    "ripgrep-all",
    "sd",
    "starship",
    "taskwarrior-tui",
    "tmuxp",
    "trash-cli",
    "ugrep",
    "yazi",
    "zoxide",
    "zsh-autocomplete",
    "zsh-completions",
    "zsh-syntax-highlighting",
    #########-Hyprland-#########
    "capitaine-cursors",
    "fuzzel",
    "gnome-keyring",
    "gsimplecal",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprshot",
    "hyprsunset",
    "kvantum",
    "kvantum-qt5",
    "nwg-clipman",
    "polkit-gnome",
    "qt5-wayland",
    "qt6-wayland",
    "satty",
    "seahorse",
    "snixembed",
    "swaync",
    "swayosd",
    "swww",
    "uwsm",
    "waybar",
    "xdg-desktop-portal-gnome",
    "xdg-desktop-portal-hyprland",
    ###########-Basic-###########
    "baobab",
    "base-devel",
    "bustle",
    "featherpad",
    "gnucash",
    "gocryptfs",
    "khal",
    "libreoffice-fresh",
    "coin-or-mp",  # LibreOffice Calc Solver
    "logrotate",
    "ly",
    "nemo-audio-tab",
    "nemo-fileroller",
    "pkgfile",
    "plymouth",
    "qalculate-qt",
    "qt5ct",
    "qt6ct",
    "qjournalctl",
    "unrar",  # File roller
    "wl-clipboard",
    "wl-clip-persist",
    "xdg-user-dirs",
    ###########-Coding-###########
    "clang",
    "inotify-tools",  # nvim
    "npm",
    "neovim-lspconfig",
    "rust",
    "uv",
    # Language Servers
    "bash-language-server",
    "lua-language-server",
    "pyright",
    "rust-analyzer",
    "systemd-language-server",
    "tailwindcss-language-server",
    "vscode-json-languageserver",
    "yaml-language-server",
    # Linters
    "ruff",
    # Tree sitter
    "tree-sitter-bash",
    "tree-sitter-cli",
    "tree-sitter-javascript",
    "tree-sitter-python",
    "tree-sitter-rust",
    #########-SQL Server-##########
    "dbeaver",
    "jdk-openjdk",
    "mariadb",
    "python-pymysql",
    ###########-Python-###########
    "python-dbus-fast",  # loggy
    "python-gnupg",  # noah
    "python-imaplib2",  # emailcheck
    "python-mpd2",
    "python-pandas",
    "python-pydantic",  # noah
    "python-pyperclip",  # noah
    "python-systemd",  # loggy
    "python-wand",  # wallpaper script
    ###########-Gaming-###########
    "gnome-chess",
    "gnuchess",
    "lib32-mangohud",
    "lutris",
    "mangohud",
    "mgba-qt",
    "steam",
    "umu-launcher",
    "vkd3d",
    "wine-mono",
    "wine-staging",
    "winetricks",
    ########-CHAOTIC PKGS-########
    "anki",
    "ayugram-desktop-git",
    "qt6-imageformats",  # AyuGram missing dependency
    "betterbird-bin",
    "dxvk-mingw-git",
    "firedragon",
    "logiops",
    "nchat-git",
    "neovim-symlinks",
    "ocrmypdf",
    "octopi",
    "paru",
    "proton-ge-custom-bin",
    "rpcs3-git",
]
