arch_config_json = {
    "app_config": {
        "audio_config": {"audio": "pipewire"},
        "bluetooth_config": {"enabled": True},
        "firewall_config": {"firewall": "firewalld"},
        "fonts_config": {"fonts": ["noto-fonts-emoji", "ttf-liberation"]},
        "power_management_config": {"power_management": "tuned"},
        "print_service_config": {"enabled": False},
    },
    "archinstall-language": "English",
    "bootloader_config": {"bootloader": "Limine", "removable": False, "uki": False},
    "hostname": "yulia",
    "kernels": ["linux"],
    "locale_config": {"kb_layout": "us", "sys_enc": "UTF-8", "sys_lang": "en_US.UTF-8"},
    "optional_repositories": ["multilib"],
    "network_config": {"type": "iso"},
    "ntp": True,
    "packages": [],
    "pacman_config": {"color": True, "parallel_downloads": 10},
    "services": [
        "ananicy-cpp",
        "iwd",
        "named",
        "swayosd-libinput-backend",
        "systemd-networkd",
        "systemd-oomd",
        "btrfs-scrub@-.timer",
        "btrfs-scrub@home.timer",
        "fstrim.timer",
        "logrotate.timer",
        "man-db.timer",
        "paccache.timer",
        "reflector.timer",
        "snapper-timeline.timer",
        "snapper-cleanup.timer",
        "loggy",
        "sysinfo",
    ],
    "swap": {"algorithm": "zstd", "enabled": True},
    "timezone": "US/Eastern",
    "version": "4.3",
}
json_config = {
    "parallel_downloads": 10,
    "terminal": "kitty",
    "firefox_browser": "floorp",
    "dots_repo": "polka",
    "git_user": "acctux",
    "ssh_key_file": "id_ed25519",
    "gpg_key_file": "my_sec_gpg.asc",
    "master_pass_file": "pass.txt",
    "my_pass": "users.json",
    "reflector_options": [
        "--country US",
        "--protocol https",
        "--latest 15",
        "--sort rate",
        "--number 3",
        "--save /etc/pacman.d/mirrorlist",
    ],
    "disable_svcs": [
        "systemd-resolved",
        "systemd-networkd-wait-online",
    ],
    "no_extracts": [
        "etc/xdg/autostart/firewall-applet.desktop",
        "usr/share/icons/capitaine-cursors/*",
    ],
    "copy_config": {
        "files_to_cp": [
            {
                "source_dir": "noahinstall",
                "target_dirs": [
                    {"dest": ".ssh", "names": ["id_ed25519", "pass.txt"]},
                    {"dest": "", "names": ["users.json", "chaotic.key"]},
                    {"dest": ".gnupg", "names": ["my_sec_gpg.asc"]},
                ],
            }
        ],
        "dir_contents_to_cp": [
            {
                "source_dir": "noahinstall",
                "target_dir": "/etc/wireguard",
                "names": ["wireguard"],
            }
        ],
    },
    "user_services": [
        {
            "source": "/usr/lib/systemd/user",
            "targets": [
                {
                    "target": "default",
                    "serv": [
                        "psd.service",
                    ],
                },
                {
                    "target": "sockets",
                    "serv": [
                        "gcr-ssh-agent.socket",
                        "mpd.socket",
                    ],
                },
                {
                    "target": "graphical-session",
                    "serv": [
                        "cliphist.service",
                        "hypridle.service",
                        "hyprsunset.service",
                        "swaync.service",
                        "waybar.service",
                    ],
                },
            ],
        },
        {
            "source": ".config/systemd/user",
            "targets": [
                {
                    "target": "graphical-session",
                    "serv": [
                        "ayugram.service",
                        "clip-persist.service",
                        "kdeconnectd.service",
                        "kanshi.service",
                        "playerctld.service",
                        "polkit-gnome.service",
                        "snixembed.service",
                        "swayosd.service",
                        "awww-daemon.service",
                    ],
                },
                {
                    "target": "graphical-session",
                    "serv": [
                        "emailcheck.timer",
                        "task-reminder.timer",
                        "task-schedule.timer",
                        "wall.timer",
                    ],
                },
            ],
        },
    ],
    "apps_to_hide": [
        "avahi-discover",
        "bssh",
        "btop",
        "bvnc",
        "jshell-java-openjdk",
        "jconsole-java-openjdk",
        "libreoffice-base",
        "libreoffice-draw",
        "libreoffice-impress",
        "libreoffice-math",
        "khal",
        "kvantummanager",
        "nvtop",
        "octopi-cachecleaner",
        "octopi-notifier",
        "octopi-repoeditor",
        "org.gnome.baobab",
        "org.kde.kdeconnect.nonplasma",
        "qt5ct",
        "qt6ct",
        "qv4l2",
        "qvidcap",
        "scrcpy-console",
        "taskwarrior-tui",
        "tuned-gui",
        "uuctl",
        "xgps",
        "xgpsspeed",
    ],
    "encrypted_dir": "Desktop/Private",
    "git_repos": [
        {
            "username": "acctux",
            "repos": [
                {"repo_name": "noah", "repo_dest": "Lit/noah"},
                {"repo_name": "polka", "repo_dest": "Lit/polka"},
                {"repo_name": "docs", "repo_dest": "Lit/Docs"},
            ],
        }
    ],
    "dirs_to_link": [
        "local/bin",
    ],
    "dirs_icons": {
        "Desktop/Games": "folder-games",
        "Desktop/Encrypted": "folder-locked",
        "Lit": "folder-github",
        "Lit/noah": "folder-root",
        "Lit/Docs": "folder-bookmark",
        "Lit/polka": "folder-html",
    },
    "yazi_plugins": [
        "yazi-rs/plugins:jump-to-char",
        "uhs-robert/sshfs",
        "boydaihungst/gvfs",
        "uhs-robert/recycle-bin",
        "h-hg/yamb",
    ],
}
