archinstall_json = {
    "app_config": {
        "audio_config": {"audio": "pipewire"},
        "bluetooth_config": {"enabled": True},
        "firewall_config": {"firewall": "firewalld"},
        "fonts_config": {"fonts": ["noto-fonts-emoji", "ttf-liberation"]},
        "power_management_config": {"power_management": "tuned"},
        "print_service_config": {"enabled": False},
    },
    "archinstall-language": "English",
    "bootloader_config": {"bootloader": "Limine", "removable": False, "uki": False},
    "hostname": "yulia",
    "kernels": ["linux"],
    "locale_config": {"kb_layout": "us", "sys_enc": "UTF-8", "sys_lang": "en_US.UTF-8"},
    "optional_repositories": ["multilib"],
    "network_config": {"type": "iso"},
    "ntp": True,
    "packages": [],
    "pacman_config": {"color": True, "parallel_downloads": 10},
    "profile_config": {
        "gfx_driver": "AMD / ATI (open-source)",
        "greeter": "ly",
        "profile": {"details": ["Minimal"]},
    },
    "services": [
        "ananicy-cpp",
        "iwd",
        "named",
        "swayosd-libinput-backend",
        "systemd-networkd",
        "systemd-oomd",
        "btrfs-scrub@-.timer",
        "btrfs-scrub@home.timer",
        "fstrim.timer",
        "logrotate.timer",
        "man-db.timer",
        "paccache.timer",
        "reflector.timer",
        "loggy",
        "sysinfo",
    ],
    "swap": {"algorithm": "zstd", "enabled": True},
    "timezone": "US/Eastern",
    "version": "4.3",
}
noah_json = {
    "parallel_downloads": 10,
    "terminal": "kitty",
    "firefox_browser": "firedragon",
    "dots_repo": "polka",
    "git_user": "acctux",
    "reflector_country": "US",
    "disable_svcs": [
        "systemd-resolved",
        "systemd-networkd-wait-online",
    ],
    "no_extracts": [
        "etc/xdg/autostart/firewall-applet.desktop",
        "usr/share/icons/capitaine-cursors/*",
    ],
    "key_copy_config": {
        "source_dir": "noahinstall",
        "target_dir": ".ssh",
        "keys": {
            "ssh_key": "id_ed25519",
            "gpg_key": "my_sec_gpg.asc",
            "master_pass": "pass.txt",
            "auth_conf": "users.json",
        },
    },
    "additional_usb_to_cp": [
        {
            "source_dir": "noahinstall",
            "target_dir": "",
            "names": ["chaotic.key"],
        }
    ],
    "dir_contents_to_cp": [
        {
            "source_dir": "noahinstall",
            "target_dir": "/etc",
            "names": ["wireguard"],
        }
    ],
    "user_services": [
        {
            "source": "/usr/lib/systemd/user",
            "target": "default",
            "servs": ["psd.service"],
        },
        {
            "source": "/usr/lib/systemd/user",
            "target": "sockets",
            "serv": [
                "gcr-ssh-agent.socket",
                "mpd.socket",
            ],
        },
        {
            "source": "/usr/lib/systemd/user",
            "target": "graphical-session",
            "serv": [
                "cliphist.service",
                "hypridle.service",
                "hyprsunset.service",
                "swaync.service",
                "waybar.service",
            ],
        },
        {
            "source": ".config/systemd/user",
            "target": "graphical-session",
            "serv": [
                "ayugram.service",
                "clip-persist.service",
                "kdeconnectd.service",
                "kanshi.service",
                "playerctld.service",
                "polkit-gnome.service",
                "snixembed.service",
                "swayosd.service",
                "awww-daemon.service",
            ],
        },
        {
            "source": ".config/systemd/user",
            "target": "timers",
            "serv": [
                "emailcheck.timer",
                "task-reminder.timer",
                "task-schedule.timer",
                "wall.timer",
            ],
        },
    ],
    "apps_to_hide": [
        "avahi-discover",
        "bssh",
        "btop",
        "bvnc",
        "jshell-java-openjdk",
        "jconsole-java-openjdk",
        "libreoffice-base",
        "libreoffice-draw",
        "libreoffice-impress",
        "libreoffice-math",
        "khal",
        "kvantummanager",
        "nvtop",
        "octopi-cachecleaner",
        "octopi-notifier",
        "octopi-repoeditor",
        "org.gnome.baobab",
        "org.kde.kdeconnect.nonplasma",
        "qt5ct",
        "qt6ct",
        "qv4l2",
        "qvidcap",
        "scrcpy-console",
        "taskwarrior-tui",
        "tuned-gui",
        "uuctl",
        "xgps",
        "xgpsspeed",
    ],
    "sudo_defaults": [
        "insults",
        "passwd_tries=10",
        "lecture=never",
        "passwd_timeout=0",
        "timestamp_timeout=20",
        "pwfeedback",
        "timestamp_type=global",
        "editor=/usr/sbin/nvim, !env_editor",
    ],
    "encrypted_dir": "Desktop/Private",
    "git_repo_config": {
        "user_name": "acctux",
        "repos": {
            "noah": "Lit/noah",
            "polka": "Lit/polka",
            "docs": "Lit/Docs",
        },
    },
    "dotfiles_config": {
        "dotfiles_dir": "Lit/polka",
        "secret_dotfiles_dir": "Lit/Docs/secdots",
        "dirs_to_link": [
            "local/bin",
        ],
    },
    "dirs_icons": {
        "Desktop/Games": "folder-games",
        "Desktop/Encrypted": "folder-locked",
        "Lit": "folder-github",
        "Lit/noah": "folder-root",
        "Lit/Docs": "folder-bookmark",
        "Lit/polka": "folder-html",
    },
    "yazi_plugins": [
        "yazi-rs/plugins:jump-to-char",
        "uhs-robert/sshfs",
        "boydaihungst/gvfs",
        "uhs-robert/recycle-bin",
        "h-hg/yamb",
    ],
}
