#!/usr/bin/env bash

# --------------------------------------------------------------------------------------
# ███╗   ██╗  ██████╗   █████╗  ██╗  ██╗  ██████╗     █████╗  ██████╗   ██████╗ ██╗  ██╗
# ████╗  ██║ ██╔═══██╗ ██╔══██╗ ██║  ██║ ██╔════╝    ██╔══██╗ ██╔══██╗ ██╔════╝ ██║  ██║
# ██╔██╗ ██║ ██║   ██║ ███████║ ███████║ ╚█████╗     ███████║ ██████╔╝ ██║      ███████║
# ██║╚██╗██║ ██║   ██║ ██╔══██║ ██╔══██║  ╚═══██╗    ██╔══██║ ██╔══██╗ ██║      ██╔══██║
# ██║ ╚████║ ╚██████╔╝ ██║  ██║ ██║  ██║ ██████╔╝    ██║  ██║ ██║  ██║ ╚██████╗ ██║  ██║
# ╚═╝  ╚═══╝  ╚═════╝  ╚═╝  ╚═╝ ╚═╝  ╚═╝ ╚═════╝     ╚═╝  ╚═╝ ╚═╝  ╚═╝  ╚═════╝ ╚═╝  ╚═╝
# --------------------------------------------------------------------------------------
# The one-opinion opinionated automated Arch Linux Installer
# --------------------------------------------------------------------------------------
set -euo pipefail

#############################################################################
#  TODO:
#  1. figure out what to do about wifi/internet
#     it's commented out
#  2. bootloaders needs research
#  3. read previous password files
#  3. GPU drivers NVIDIA
#  4. add etckeeper init
#  5. ensure correct chmod
#  7. Greetings/ending
#  9. Add "hide-apps"
#
#############################################################################
set -a
SCRIPT_D="$(dirname "${BASH_SOURCE[0]}")"
OUT_D="$SCRIPT_D/outside"
set +a

. "$SCRIPT_D/user-config"
. "$SCRIPT_D/utils"

#######################################
# Main
#######################################
noah() {
  # bash "${OUT_D}/outside-env.sh"
  arch-chroot /mnt $HOME/${INSTALL_SCRIPT}/inside/inside-env.sh
  arch-chroot /mnt /usr/bin/runuser -u $USER_NAME -- /home/$USER_NAME/${INSTALL_SCRIPT}/user/user-env.sh
  # arch-chroot /mnt $HOME/ArchTitus/scripts/3-post-setup.sh
}
noah

trap 'error_trap ${LINENO} "$BASH_COMMAND"' ERR
