pacman_pkgs: dict[str, list[str]] = {
    "base": [
        # HARDWARE
        "ananicy-cpp",
        "apparmor",
        "bluetui",
        "bluez-utils",  # for loggy
        "brightnessctl",
        "btop",
        "cliphist",
        "rocm-smi-lib",  # btop dependency for amd gpu
        "dmidecode",
        "dosfstools",
        "exfatprogs",
        "hwdetect",
        "kanshi",
        "kitty",
        "less",
        "mcfly",
        "ntfs-3g",
        "smartmontools",
        "udisks2-btrfs",
        "usb_modeswitch",
        "powertop",
        "gnome-logs",
        "systemctl-tui",
        "base-devel",
        "logrotate",
        "plymouth",
        "rebuild-detector",
        "reflector",
        "xdg-user-dirs",
        "zsh-autocomplete",
        "zsh-completions",
        "zsh-syntax-highlighting",
        "starship",
        "trash-cli",
        "pkgfile",
        # Network
        "bind",
        "impala",
        "iw",
        "openresolv",
        "wireguard-tools",
        "networkmanager",
        # media
        "cava",
        "imv",
        "mpd",
        "mpd-mpris",
        "mpv-mpris",
        "pavucontrol",
        "playerctl",
        "rmpc",
        # Hypr
        "capitaine-cursors",
        "fuzzel",
        "gnome-keyring",
        "hypridle",
        "hyprland",
        "hyprlock",
        "hyprshot",
        "hyprsunset",
        "kvantum",
        "kvantum-qt5",
        "polkit-gnome",
        "qt5-wayland",
        "qt6-wayland",
        "satty",
        "seahorse",
        "snixembed",
        "swaync",
        "swayosd",
        "awww",
        "uwsm",
        "waybar",
        "xdg-desktop-portal-gnome",
        "xdg-desktop-portal-hyprland",
        # Python
        "python-dbus-fast",  # loggy
        "python-gnupg",  # noah
        "python-imaplib2",  # emailcheck
        "python-pandas",  # weather
        "python-pydantic",  # noah
        "python-pyperclip",  # noah
        "python-systemd",  # loggy
        "python-wand",  # wallpaper script
        "otf-firamono-nerd",
        "inotify-tools",  # nvim
        "npm",
        "neovim-lspconfig",
        "uv",
        "qt5ct",
        "qt6ct",
        "wl-clipboard",
        "wl-clip-persist",
        "yazi",
        "zbar",  # qr codes
        "qrencode",  # qr codes
        "git-delta",
        "taskwarrior-tui",
        "man-pages",
        "rofimoji",
        "bat-extras",
        "eza",
        "fd",
        "fzf",
        "lazygit",
        "ripgrep-all",
        "sd",
        "file-roller",
        "unrar",  # File roller
        "gocryptfs",
        "zathura-pdf-mupdf",
        "zoxide",
    ],
    "language": [
        "hunspell-en_us",
        "hyphen-en",
        "tesseract-data-eng",
        "tesseract-data-rus",
        "tesseract-data-ukr",
    ],
    "chaotic_repo": [
        "apparmor.d-git",
        "cachyos-ananicy-rules-git",
        "downgrade",
        "floorp",
        "octopi",
        "paru",
        "systemd-oomd-defaults",
        "ocrmypdf",
    ],
    "printer": [
        "cups",
        "cups-browsed",
        "cups-filters",
        "cups-pdf",
        "foomatic-db",
        "foomatic-db-engine",
        "foomatic-db-gutenprint-ppds",
        "foomatic-db-nonfree",
        "foomatic-db-nonfree-ppds",
        "foomatic-db-ppds",
        "ghostscript",
        "gsfonts",
        "gutenprint",
        "simple-scan",
        "splix",
        "system-config-printer",
    ],
    "limine": [
        "limine-snapper-sync",
        "limine-mkinitcpio-hook",
    ],
    "extra": [
        "profile-sync-daemon",
        "protonmail-bridge-core",
        "termscp",
        "wireshark-cli",
        "github-cli",
        # coding
        # Language Servers
        "bash-language-server",
        "lua-language-server",
        "rust-analyzer",
        "tombi",
        "ty",
        "vscode-css-languageserver",
        "vscode-json-languageserver",
        "yaml-language-server",
        # Formatters
        "ruff",
        "shfmt",
        # Lint
        "shellcheck",
        "biome",
        "luacheck",
        "yamllint",
        # Tree sitter
        "tree-sitter-bash",
        "tree-sitter-cli",
        "tree-sitter-python",
        "tmuxp",
        "rust",
        "stylua",
        "yamlfmt",
        "tree-sitter-rust",
        "deluge-gtk",
        "nvtop",
        "jolt",
        "ugrep",
        "anki",
        "authenticator",
        "baobab",
        "bustle",
        "partitionmanager",
        "qalculate-qt",
        "evince",
        "gimp",
        "guvcview",
        "yt-dlp",  # for mpv youtube playback
        "libreoffice-fresh",
        "coin-or-mp",  # LibreOffice Calc Solver
        "gnucash",
        "kdeconnect",
        "gvfs-mtp",
        "sshfs",
        "scrcpy",
        "gvfs-afc",
        "gvfs-gphoto2",
        "usbmuxd",
        "dbeaver",
        "jdk-openjdk",
        "mariadb",
        "python-pymysql",
        "gnome-chess",
        "gnuchess",
        "lib32-mangohud",
        "lutris",
        "mangohud",
        "mgba-qt",
        "steam",
        "umu-launcher",
        "wine-mono",
        "wine-staging",
        "winetricks",
    ],
    "extra_chaos": [
        "logiops",
        "neovim-symlinks",
        "ayugram-desktop-git",
        "qt6-imageformats",  # AyuGram missing dependency
        "betterbird-bin",
        "linux-headers",
        "xpadneo-dkms",
        "nchat-git",
        "proton-cachyos-slr",
        "rpcs3-git",
        "eden-git",
    ],
}
aur_pkgs: list[str] = [
    "wvkbd-deskintl",
]
