#!/usr/bin/env bash

# --------------------------------------------------------------------------------------
# ███╗   ██╗  ██████╗   █████╗  ██╗  ██╗  ██████╗     █████╗  ██████╗   ██████╗ ██╗  ██╗
# ████╗  ██║ ██╔═══██╗ ██╔══██╗ ██║  ██║ ██╔════╝    ██╔══██╗ ██╔══██╗ ██╔════╝ ██║  ██║
# ██╔██╗ ██║ ██║   ██║ ███████║ ███████║ ╚█████╗     ███████║ ██████╔╝ ██║      ███████║
# ██║╚██╗██║ ██║   ██║ ██╔══██║ ██╔══██║  ╚═══██╗    ██╔══██║ ██╔══██╗ ██║      ██╔══██║
# ██║ ╚████║ ╚██████╔╝ ██║  ██║ ██║  ██║ ██████╔╝    ██║  ██║ ██║  ██║ ╚██████╗ ██║  ██║
# ╚═╝  ╚═══╝  ╚═════╝  ╚═╝  ╚═╝ ╚═╝  ╚═╝ ╚═════╝     ╚═╝  ╚═╝ ╚═╝  ╚═╝  ╚═════╝ ╚═╝  ╚═╝
# --------------------------------------------------------------------------------------
# The one-opinion opinionated automated Arch Linux Installer
# --------------------------------------------------------------------------------------

#######################################
# Groups/Services
#######################################
INSTALL_SCRIPT="noah"
TIMEZONE="US/Eastern"
HOST_NAME="yulia"
USER_NAME="nick"
LOCALE="en_US.UTF-8"
DEFAULT_EFI_SIZE="512MiB"
BOOTLOADER="systemd-boot"
ROOT_LABEL="Arch"
KEY_DIR=".ssh"
WIFI_PASS_DIR="$KEY_DIR"
ICON_GIT="https://github.com/vinceliuice/WhiteSur-icon-theme.git"
KEYMAP="us"
MOUNT_OPTIONS="noatime,compress=zstd"

#######################################
# Groups/Services
#######################################
PKG_LISTS=(
  business
  chaotic
  cli-tools
  coding
  desktop
  gaming
  hardware
  hyprland
  language-fonts
  multimedia
  networking
)

#######################################
# Groups/Services
#######################################
USER_GROUPS=(
  wheel
  power
  input
  audio
  video
  network
  storage
  rfkill
  log
  games
  gamemode
)

#######################################
# Sysd services
#######################################
SYSD_ENABLE=(
  acpid.service
  ananicy-cpp.service
  avahi-daemon.service
  bluetooth.service
  ly.service
  NetworkManager.service
  ntpd.service
  tlp.service
  unbound.service
  write-tlp-config.service
  fstrim.timer
  logrotate.timer
  man-db.timer
  paccache.timer
  reflector.timer
  roothints.timer
)
SYSD_DISABLE=(
  systemd-timesyncd
)

#######################################
# User services
#######################################
USER_SERV_ENABLE=(
  gnome-keyring-daemon.service
  hypridle.service
  hyprpolkitagent.service
  mako.service
  pipewire.service
  pipewire-pulse.service
  wireplumber.service
  waybar.service
  wall.timer
  gcr-ssh-agent.socket
)

#######################################
# Git
#######################################
DOT_URL="https://github.com/acctux/polka.git"
GIT_USER="acctux"
LIT_DIR="Lit"
LIT_REPOS=(
  "docs"
  "noah"
)

#######################################
# Keys
#######################################
SSH_KEYFILE="id_ed25519"
GPG_KEYFILE="my-private-key.asc"
MY_PASS="pass.asc"
KEY_FILES=(
  "$SSH_KEYFILE"
  "$GPG_KEYFILE"
  "$MY_PASS"
)

#######################################
# Folders
#######################################
declare -A CUSTOM_FOLDERS=(
  ICON_DIR="$HOME/.local/share/icons"
  ["$HOME/Games"]="$ICON_DIR/places/scalable/folder-games.svg"
  ["$HOME/Lit"]="$ICON_DIR/places/scalable/folder-github.svg"
  ["$HOME/Polka"]="$ICON_DIR/places/scalable/folder-html.svg"
  ["$HOME/Overload"]="$ICON_DIR/places/scalable/folder-root.svg"
)
readonly -A CUSTOM_FOLDERS

REMOVE_XDG_DIRS=(
  "XDG_PUBLICSHARE_DIR"
  "XDG_DESKTOP_DIR"
)
