// vim:set ts=4 sw=4 et:
tls google {
    remote-hostname "dns.google";
};
options {
	pid-file "/run/named/named.pid";
    directory "/var/named";
    max-cache-size 200m;
    listen-on { 127.0.0.1; };
    listen-on-v6 { ::1; };
    allow-recursion { 
    	127.0.0.1; 
    	::1;
    };
    forward only;
    forwarders port 853 tls google {
        8.8.8.8; 2001:4860:4860::8888;
        8.8.4.4; 2001:4860:4860::8844;
    };
// if system time is wrong and can't connect
//    dnssec-validation no;
};
zone "localhost" IN {
    type master;
    file "localhost.zone";
};
zone "0.0.127.in-addr.arpa" IN {
    type master;
    file "127.0.0.zone";
};
